server:
  port: 9000

security:
  oauth2:
    client:
      client-id: client1
      client-secret: utsav
      access-token-uri: http://localhost:9000/oauth/token
      #user-authorization-uri: http://localhost:9000/user
          
      
         
